// Generated by `superset plugins publish`. Do not edit.
//
// The first-party marketplace's published manifests, bundled so the API can
// resolve a plugin without fetching anything. This is deliberately not
// client-supplied: a manifest drives token_url and the proxy target, so
// trusting one from a request would be an exfiltration path.

export const FIRST_PARTY_MANIFESTS = {
	"github": {
		"$schema": "https://superset.sh/schemas/plugin/1.0.0.json",
		"name": "github",
		"version": "1.0.0",
		"description": "Work with issues, pull requests, and CI across your repositories.",
		"author": {
			"name": "Superset",
			"url": "https://superset.sh"
		},
		"homepage": "https://docs.superset.sh",
		"repository": "https://github.com/superset-sh/superset",
		"license": "MIT",
		"keywords": [
			"github",
			"issues",
			"pull-requests",
			"ci",
			"code-review"
		],
		"extensions": {
			"superset": {
				"interface": {
					"displayName": "GitHub",
					"category": "Developer tools",
					"icon": "github"
				},
				"auth": [
					{
						"type": "oauth2",
						"provider": "github",
						"authorization_url": "https://github.com/login/oauth/authorize",
						"token_url": "https://github.com/login/oauth/access_token",
						"scopes": [
							"repo",
							"read:org",
							"workflow"
						],
						"scope_separator": " ",
						"token_request_auth_method": "client_secret_post",
						"requires_env": [
							"PLUGIN_GITHUB_CLIENT_ID",
							"PLUGIN_GITHUB_CLIENT_SECRET"
						],
						"identity": {
							"url": "https://api.github.com/user",
							"method": "GET",
							"headers": {
								"Authorization": "Bearer ${config.access_token}",
								"Accept": "application/vnd.github+json"
							},
							"id": "$.id",
							"label": "$.login"
						},
						"label": "OAuth 2.0",
						"bind": {
							"headers": {
								"Authorization": "Bearer ${config.access_token}"
							}
						}
					}
				],
				"mcp": {
					"type": "streamable-http",
					"url": "https://api.githubcopilot.com/mcp/"
				}
			}
		},
		"skills": [
			{
				"name": "ci-triage",
				"description": "Diagnose a failing GitHub Actions run — find the first real error in the logs, tell a flake apart from a genuine failure, and identify the commit that broke it. Use when checks are red on a PR, a workflow failed, the build is broken, CI is flaky, or the user asks why a run failed or whether a failure is real."
			},
			{
				"name": "issue-triage",
				"description": "Triage a GitHub issue into something actionable — reproduce the claim, find duplicates, judge severity, and apply labels, milestone, and assignee. Use when the user asks to triage an issue, sort the backlog, deal with new issues, check whether a bug is already reported, or says \"what should we do with this issue\"."
			}
		]
	} as const,
	"linear": {
		"$schema": "https://superset.sh/schemas/plugin/1.0.0.json",
		"name": "linear",
		"version": "1.0.0",
		"description": "Plan and build products: create, search, and update Linear issues.",
		"author": {
			"name": "Superset",
			"url": "https://superset.sh"
		},
		"homepage": "https://docs.superset.sh",
		"repository": "https://github.com/superset-sh/superset",
		"license": "MIT",
		"keywords": [
			"linear",
			"issues",
			"project-management",
			"planning"
		],
		"extensions": {
			"superset": {
				"interface": {
					"displayName": "Linear",
					"category": "Productivity",
					"icon": "linear"
				},
				"auth": [
					{
						"type": "oauth2",
						"label": "OAuth 2.0",
						"provider": "linear",
						"authorization_url": "https://linear.app/oauth/authorize",
						"token_url": "https://api.linear.app/oauth/token",
						"scopes": [
							"read",
							"write",
							"issues:create"
						],
						"scope_separator": ",",
						"token_request_auth_method": "client_secret_post",
						"token_expiration_buffer": 300,
						"requires_env": [
							"PLUGIN_LINEAR_CLIENT_ID",
							"PLUGIN_LINEAR_CLIENT_SECRET"
						],
						"identity": {
							"url": "https://api.linear.app/graphql",
							"method": "POST",
							"headers": {
								"Authorization": "Bearer ${config.access_token}",
								"Content-Type": "application/json"
							},
							"body": {
								"query": "query { viewer { id name organization { id name } } }"
							},
							"id": "$.data.viewer.organization.id",
							"label": "$.data.viewer.organization.name"
						},
						"bind": {
							"headers": {
								"Authorization": "Bearer ${config.access_token}"
							}
						}
					},
					{
						"type": "api_key",
						"label": "Personal API key",
						"credential_input": "api_key",
						"inputs": [
							{
								"name": "api_key",
								"label": "Linear API key",
								"placeholder": "lin_api_…",
								"description": "Linear → Settings → Security & access → Personal API keys",
								"required": true,
								"secret": true
							}
						],
						"identity": {
							"url": "https://api.linear.app/graphql",
							"method": "POST",
							"headers": {
								"Authorization": "${config.access_token}",
								"Content-Type": "application/json"
							},
							"body": {
								"query": "query { viewer { id name organization { id name } } }"
							},
							"id": "$.data.viewer.organization.id",
							"label": "$.data.viewer.organization.name"
						},
						"bind": {
							"headers": {
								"Authorization": "${config.access_token}"
							}
						}
					}
				]
			}
		},
		"skills": []
	} as const,
} as const;

export type FirstPartyPluginName = keyof typeof FIRST_PARTY_MANIFESTS;

export function firstPartyManifest(
	name: string,
): (typeof FIRST_PARTY_MANIFESTS)[FirstPartyPluginName] | null {
	return (
		(FIRST_PARTY_MANIFESTS as Record<string, unknown>)[name] as
			| (typeof FIRST_PARTY_MANIFESTS)[FirstPartyPluginName]
			| undefined
	) ?? null;
}
